Piteste/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Piteste.Models
{
    public class Pessoa
    {
        public int PessoaID { get; set; }
        public string PessoaEmail { get; set; }
        public string PessoaSenha { get; set; }
        public int PessoaTipo { get; set; }
    }
}

Piteste/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piteste.Models;

namespace Piteste.Controllers
{
    public class AlunosController : Controller
    {
        private Context db = new Context();

        // GET: Alunos
        public ActionResult Index()
        {
            var alunos = db.Alunos.Include(a => a.Classe).Include(a => a.Responsavel);
            return View(alunos.ToList());
        }
        public ActionResult HomeAluno()
        {
            return View();
        }
        // GET: Alunos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        // GET: Alunos/Create
        public ActionResult Create()
        {
            ViewBag.ClasseID = new SelectList(db.Classes, "ClasseID", "Nome");
            ViewBag.ResponsavelID = new SelectList(db.Responsaveis, "ResponsavelID", "CpfResponsavel");
            return View();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlunoID,EnderecoAluno,AtivoAluno,NomeAluno,CpfAluno,ClasseID,ResponsavelID,TipoAluno")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Alunos.Add(aluno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClasseID = new SelectList(db.Classes, "ClasseID", "Nome", aluno.ClasseID);
            ViewBag.ResponsavelID = new SelectList(db.Responsaveis, "ResponsavelID", "CpfResponsavel", aluno.ResponsavelID);
            return View(aluno);
        }

        // GET: Alunos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClasseID = new SelectList(db.Classes, "ClasseID", "Nome", aluno.ClasseID);
            ViewBag.ResponsavelID = new SelectList(db.Responsaveis, "ResponsavelID", "CpfResponsavel", aluno.ResponsavelID);
            return View(aluno);
        }

        // POST: Alunos/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlunoID,EnderecoAluno,AtivoAluno,NomeAluno,CpfAluno,ClasseID,ResponsavelID,TipoAluno")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aluno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClasseID = new SelectList(db.Classes, "ClasseID", "Nome", aluno.ClasseID);
            ViewBag.ResponsavelID = new SelectList(db.Responsaveis, "ResponsavelID", "CpfResponsavel", aluno.ResponsavelID);
            return View(aluno);
        }

        // GET: Alunos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aluno aluno = db.Alunos.Find(id);
            db.Alunos.Remove(aluno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piteste/Controllers/AnoLetivosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piteste.Models;

namespace Piteste.Controllers
{
    public class AnoLetivosController : Controller
    {
        private Context db = new Context();

        // GET: AnoLetivos
        public ActionResult Index()
        {
            return View(db.Anos.ToList());
        }

        // GET: AnoLetivos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnoLetivo anoLetivo = db.Anos.Find(id);
            if (anoLetivo == null)
            {
                return HttpNotFound();
            }
            return View(anoLetivo);
        }

        // GET: AnoLetivos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnoLetivos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AnoLetivoID,Ano,Ativo")] AnoLetivo anoLetivo)
        {
            if (ModelState.IsValid)
            {
                db.Anos.Add(anoLetivo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(anoLetivo);
        }

        // GET: AnoLetivos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnoLetivo anoLetivo = db.Anos.Find(id);
            if (anoLetivo == null)
            {
                return HttpNotFound();
            }
            return View(anoLetivo);
        }

        // POST: AnoLetivos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AnoLetivoID,Ano,Ativo")] AnoLetivo anoLetivo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(anoLetivo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(anoLetivo);
        }

        // GET: AnoLetivos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnoLetivo anoLetivo = db.Anos.Find(id);
            if (anoLetivo == null)
            {
                return HttpNotFound();
            }
            return View(anoLetivo);
        }

        // POST: AnoLetivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnoLetivo anoLetivo = db.Anos.Find(id);
            db.Anos.Remove(anoLetivo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piteste/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piteste.Models;

namespace Piteste.Controllers
{
    public class ClassesController : Controller
    {
        private Context db = new Context();

        // GET: Classes
        public ActionResult Index()
        {
            var classes = db.Classes.Include(c => c.AnoLetivo);
            return View(classes.ToList());
        }

        // GET: Classes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Classe classe = db.Classes.Find(id);
            if (classe == null)
            {
                return HttpNotFound();
            }
            return View(classe);
        }

        // GET: Classes/Create
        public ActionResult Create()
        {
            ViewBag.AnoLetivoID = new SelectList(db.Anos, "AnoLetivoID", "AnoLetivoID");
            return View();
        }

        // POST: Classes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClasseID,Nome,Ativo,AnoLetivoID")] Classe classe)
        {
            if (ModelState.IsValid)
            {
                db.Classes.Add(classe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AnoLetivoID = new SelectList(db.Anos, "AnoLetivoID", "AnoLetivoID", classe.AnoLetivoID);
            return View(classe);
        }

        // GET: Classes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Classe classe = db.Classes.Find(id);
            if (classe == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnoLetivoID = new SelectList(db.Anos, "AnoLetivoID", "AnoLetivoID", classe.AnoLetivoID);
            return View(classe);
        }

        // POST: Classes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClasseID,Nome,Ativo,AnoLetivoID")] Classe classe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(classe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnoLetivoID = new SelectList(db.Anos, "AnoLetivoID", "AnoLetivoID", classe.AnoLetivoID);
            return View(classe);
        }

        // GET: Classes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Classe classe = db.Classes.Find(id);
            if (classe == null)
            {
                return HttpNotFound();
            }
            return View(classe);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Classe classe = db.Classes.Find(id);
            db.Classes.Remove(classe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piteste/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piteste.Models;

namespace Piteste.Controllers
{
    public class PessoasController : Controller
    {
        private Context db = new Context();

        // GET: Pessoas
        public ActionResult Index()
        {
            return View(db.Pessoas.ToList());
        }
        public ActionResult HomeAdm()
        {
            return View();
        }
        // GET: Pessoas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // GET: Pessoas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PessoaID,PessoaEmail,PessoaSenha,PessoaTipo")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Pessoas.Add(pessoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pessoa);
        }

        // GET: Pessoas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PessoaID,PessoaEmail,PessoaSenha,PessoaTipo")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pessoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pessoa);
        }

        // GET: Pessoas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pessoa pessoa = db.Pessoas.Find(id);
            db.Pessoas.Remove(pessoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piteste/Views/Pessoas/Create.cshtml
@model Piteste.Models.Pessoa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PessoaEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Piteste/Views/Pessoas/Delete.cshtml
@model Piteste.Models.Pessoa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaSenha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaSenha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaTipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Piteste/Views/Pessoas/Details.cshtml
@model Piteste.Models.Pessoa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaSenha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaSenha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaTipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PessoaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Piteste/Views/Pessoas/Edit.cshtml
@model Piteste.Models.Pessoa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PessoaID)

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Piteste/Views/Pessoas/Frequencia.cshtml
@model Piteste.Models.Aluno

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClasseID, "Classe", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ResponsavelID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ClasseID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Procurar" class="btn btn-default" />
        </div>
    </div> 
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Piteste/Views/Pessoas/HomeAdm.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title StudyUp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Study Up", "HomeAdm", "Pessoas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar Professores", "Index", "Professores")</li>
                    <li>@Html.ActionLink("Cadastrar Responsaveis", "Index", "Responsaveis")</li>
                    <li>@Html.ActionLink("Cadastrar Alunos", "Index", "Alunos")</li>
                    <li>@Html.ActionLink("Cadastrar Classe", "Index", "Classes")</li>   
                    <li>@Html.ActionLink("Ano Letivo", "Index", "AnoLetivos")</li>
                    <li>@Html.ActionLink("Sair", "Logar", "Publico")</li>
                </ul>
            </div>
        </div>
    </div>
    @{
        Piteste.Models.Pessoa pessoa = Piteste.Repositories.Funcoes.GetUsuario();
        if (pessoa != null)
        {
           
        }
        else
        {
            <script type="text/javascript">
                window.location.href = "@Url.Action("Logar","Publico")";
            </script>
        }
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

Piteste/Views/Pessoas/Index.cshtml
@model IEnumerable<Piteste.Models.Pessoa>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaSenha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaTipo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaSenha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaTipo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PessoaID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PessoaID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PessoaID })
        </td>
    </tr>
}

</table>